config/routes.rb
Rails.application.routes.draw do

  root to: 'users#index'
  get 'login', to: 'sessions#new', as: :login
  post 'login', to: 'sessions#create', as: :create_session
  get 'logout', to: 'sessions#destroy', as: :logout
  get 'signup', to: 'users#new'
  resources :users do
    get 'stats', to: 'users#stats', as: :stats
    resources :baths
  end

end

app/models/bath.rb
class Bath < ActiveRecord::Base
  # t.float    "amount_spent"
  # t.date     "date"
  # t.float    "ideal_amount"
  # t.datetime "time_spent"

  belongs_to :user

  # banho não pode ser salvo sem algum desses atributos
  # validates_presence_of :date
  # validates_presence_of :amount_spent
  # validates_presence_of :time_spent

end

app/models/user.rb
class User < ActiveRecord::Base
  # atributos do usuário
  # - first_name
  # - last_name
  # - email
  # - birthdate
  # - gender
  # - password_digest

  # usuário não pode salvar sem algum desses atributos
  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :email
  validates_presence_of :birthdate
  validates_presence_of :gender

  # email para ficar no formato de blabla@blable.bla
  validates_format_of :email, { with: /\A[\w+\-.]+@[a-z\-]+\.[a-z]+\Z/i, message: "Formato permitido: joaodasilva@provedor.com.br" }

  # email não pode ser repetido
  validates_uniqueness_of :email

  # genero pode ser apenas masculino/feminino
  validates_inclusion_of :gender, in: %w(masculino feminino)

  # a data de nascimento não pode ser maior que a data de hoje
  validate :birthdate_less_than_today

  has_many :baths

  # a senha é salva encriptada no banco
  has_secure_password

  def birthdate_less_than_today
    birthdate <= Date.today
  end

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  private

  def require_login
    if session[:user_id].present? && logged_in?
      true
    else
      redirect_to root_path
    end
  end
end

app/controllers/baths_controller.rb
class BathsController < ApplicationController
  before_filter :require_login
  before_action :set_bath, only: [:index, :show, :edit, :update, :destroy]

  # GET /baths
  # GET /baths.json
  def index
    @baths = Bath.all
    respond_to do |format|
      format.html
      format.json { render json: BathsDatatable.new(view_context, @user) }
    end
  end

  # GET /baths/1
  # GET /baths/1.json
  def show
  end

  # GET /baths/new
  def new
    @user = current_user
    @bath = Bath.new
  end

  # GET /baths/1/edit
  def edit
  end

  # POST /baths
  # POST /baths.json
  def create
    # binding.pry
    banho = params[:Banhos]
    File.open(Rails.root.join('public', banho.original_filename), 'wb') do |file|
      file.write(banho.tempfile.read)
    end
    File.open(Rails.root.join('public', banho.original_filename), 'r').each_line do |line|
      create_bath(line)
    end
    redirect_to user_baths_path(current_user.id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bath
      @user = current_user
      if @user && logged_in?
        @bath = Bath.where(user_id: @user.id)
      else
        redirect_to 'root'
      end
    end

    def create_bath(baths_arr)
      bath_json = JSON.parse(baths_arr)
      amount_spent = 0.0
      time_spent = 0.0
      ideal_amount = 0.0
      date = Date.today
      user_id = current_user.id

      bath_json.each do |obj|
        amount_spent += obj['amount'].to_f
        time_spent += obj['time'].to_f
        date = obj['date'].to_date
      end

      if amount_spent != 0 && time_spent != 0
        ideal_amount = (45.0 * time_spent) / 300.0
        Bath.create(user_id: user_id, time_spent: time_spent, amount_spent: amount_spent, ideal_amount: ideal_amount, date: date)
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Combinação de email/senha inválida'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # check_authorization
  before_filter :require_login, only: [:show, :edit, :update, :destroy]
  before_action :set_user

  # GET /users
  # GET /users.json
  def index

  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        log_in @user
        flash[:success] = "Bem vindo ao Ecobath!"
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def stats
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :email, :last_name, :birthdate, :gender, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/baths_helper.rb
module BathsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.first_name, class: "gravatar")
  end
end

app/views/baths/_form.html.erb
<%= form_tag(user_baths_path(@user.id), multipart: true, method: "post") do |f| %>

  <label for="file">File to Upload</label><%= file_field_tag 'Banhos' %>

  <%= submit_tag 'enviar'%>
<% end %>

app/views/baths/edit.html.erb
<h1>Editing Bath</h1>

<%= render 'form' %>

<%= link_to 'Show', @bath %> |
<%= link_to 'Back', baths_path %>

app/views/baths/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Histórico de banhos</h1>

<table id="baths" class="display" data-source="<%= user_baths_path(format: 'json')%>">
  <thead>
    <tr>
      <th class="table-header">Data</th>
      <th class="table-header">Quantidade gasta</th>
      <th class="table-header">Tempo gasto</th>
      <th class="table-header">Quantidade ideal</th>
    </tr>
  </thead>

  <tbody>
  </tbody>
</table>

<div id="legend">
  <span id="severe" class="legend">w</span><span class="legend-description">Crítico</span>
  <span id="warning" class="legend">w</span><span class="legend-description">Atenção</span>
  <span id="fine" class="legend">w</span><span class="legend-description">Ok</span>
  <span id="finer" class="legend">w</span><span class="legend-description">Bom</span>
  <span id="finest" class="legend">w</span><span class="legend-description">Ótimo</span>
</div>
<br>
<div id="new-bath-link">
  <%= link_to 'Enviar banhos',new_user_bath_path,  { class: "btn-default", style: "text-decoration: none;" } %>
<div>

<%= javascript_include_tag 'https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js' %>
<%= stylesheet_link_tag "https://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css" %>
<script type="text/javascript">
  $(document).ready(function() {
    initializeBathsDatatable("baths", updateDataTables, null);
  });


</script>

app/views/baths/new.html.erb
<h1>Novo banho</h1>

<%= render 'form' %>

app/views/layouts/_footer.html.erb
<footer id="footer">
  <div class="container">
    <div class="col-sm-4 col-sm-offset-4">
      <!-- /.social links -->
        <div class="social text-center">
          <ul>
            <li><a class="wow fadeInUp" href="https://twitter.com/"><i class="fa fa-twitter"></i></a></li>
            <li><a class="wow fadeInUp" href="https://www.facebook.com/" data-wow-delay="0.2s"><i class="fa fa-facebook"></i></a></li>
            <li><a class="wow fadeInUp" href="https://plus.google.com/" data-wow-delay="0.4s"><i class="fa fa-google-plus"></i></a></li>
            <li><a class="wow fadeInUp" href="https://instagram.com/" data-wow-delay="0.6s"><i class="fa fa-instagram"></i></a></li>
          </ul>
        </div>
      <a href="#" class="scrollToTop"><i class="pe-7s-up-arrow pe-va"></i></a>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<head>
  <title>EcoBath - Seu gerenciador de gastos de &aacute;gua</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta name="version" content="<%= VERSION %>">
  <link href='https://fonts.googleapis.com/css?family=Magra|Open+Sans:400,700' rel='stylesheet' type='text/css' media="all">
  <link href='https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css' rel='stylesheet' type='text/css' media="all">

  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag :application %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico', type: 'image/png' %>
  <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,100italic,300italic,400italic,700italic,900italic" %>

<script type="text/javascript">
$(document).delegate('*[data-toggle="lightbox"]', 'click', function(event) { event.preventDefault(); $(this).ekkoLightbox(); });
</script>
<script>
  new WOW().init();
</script>

</head>


<div id="menu">
  <nav class="navbar-wrapper navbar-default" role="navigation">
    <div class="container">
      <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-backyard">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <a class="navbar-brand site-name" href="#top"><%= link_to image_tag("logo2.png", :alt => "Logo", style: "width: 170px; height: 87px;"), root_path, class: "brand", :id => "logo" %></a>
      </div>
      <% if logged_in? %>
        <div id="navbar-scroll" class="collapse navbar-collapse navbar-backyard navbar-right text-center">
          <ul class="nav navbar-nav" style="margin: 7.5px -15px; font-size: 1.2em;">
            <li><%= link_to "Perfil", user_path(@current_user.id) %></li>
            <li><%= link_to "Histórico", user_baths_path(@current_user.id) %></li>
            <li><%= link_to "Estatísticas", user_stats_path(@current_user.id) %></li>
            <li class="divider"></li>
            <li><%= link_to "Sair", logout_path, method: "post" %></li>
          </ul>
        </div>
      <% else %>
        <div id="login" class="navbar-backyard navbar-right">
            <ul class="nav navbar-nav" style="margin: 7.5px -15px; font-size: 1.2em;">
              <li><%= link_to 'Login', login_path %></li>
              <li><%= link_to 'Cadastro', new_user_path %></li>
            </ul>
        </div>
      <% end %>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<body>
  <%= render 'layouts/header' %>
  <div class="fullscreen landing img-responsive" style="background-image: url(/water.jpg); max-height: 100%; max-width: 100%;">
    <div class="overlay">
      <div class="container" style="max-height:900px;min-height:760px;">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      O formulário possui <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<% provide(:title, 'Sign up') %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.text_field :first_name, class: "form-control", placeholder: 'Digite seu primeiro nome' %>
      <%= f.text_field :last_name, class: "form-control", placeholder: 'Digite seu ultimo nome' %>
      <%= f.email_field :email, class: "form-control", placeholder: 'Digite seu email' %>
      <%= f.text_field :gender, class: "form-control", placeholder: 'Digite seu sexo' %>
      <%= f.date_select :birthdate, order: [:day, :month, :year], start_year: 1916, end_year: 2016, with_css_class: true, style: "height: 34px;width: 30%;background: white;border-radius: 4px 0 0 4px;display: inline;" %>
      <%= f.password_field :password, class: "form-control", placeholder: 'Digite sua senha' %>
      <%= f.password_field :password_confirmation, class: "form-control", placeholder: 'Repita sua senha' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7">

      <!-- /.logo -->
      <div class="logo wow fadeInDown"><%= link_to image_tag("logo.png", alt: "Logo", style: "width: 550px; height: 130px;"), root_path, class: "brand", id: "logo" %></div>

      <!-- /.header paragraph -->
      <div class="landing-text wow fadeInLeft">
        <p>Ecobath é um aplicativo de controle de gastos de água durante o banho. Você pode consultar seu histórico e ver projeções de como está indo,
        ajude-nos a economizar esse bem tão precioso!</p>
      </div>

      <!-- /.header button -->
      <div class="head-btn wow fadeInLeft">
        <% if @current_user %>
          <%= link_to 'Perfil', user_path(@current_user.id), class: "btn-primary" %>
        <% else %>
          <%= link_to 'Login', login_path, class: "btn-primary" %>
          <%= link_to 'Cadastro', new_user_path, class: "btn-primary" %>
        <% end %>
      </div>

      <!-- /.phone image -->
      <div class="col-md-5">
        <% image_tag("header-phone.png", :alt => "phone", class: "header-phone img-responsive wow fadeInRight") %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Cadastro</h1>
</div>

<%= render 'form' %>

app/views/users/show.html.erb
<% provide(:title, @user.first_name) %>
<h1>
  <%= gravatar_for @user %>
  <%= @user.first_name.capitalize %>
</h1>
<h2>
  <%= @user.last_name.capitalize %>, <%= @user.first_name.capitalize %>
</h2>
<h2>
  <strong>Email:</strong>
  <%= @user.email %>
</h2>

<h2>
  <strong>Data de nascimento:</strong>
  <%= @user.birthdate %>
</h2>

<h2>
  <strong>Sexo:</strong>
  <%= @user.gender %>
</h2>
<div style="margin-top: 60px;">
  <%= link_to 'Edit', edit_user_path(@user), {class: "btn-default", style: "text-decoration: none; color: #fff;"} %>
  <%= link_to 'Back', users_path, {class: "btn-default", style: "text-decoration: none;"}%>
</div>

app/views/users/stats.html.erb
<p id="notice"><%= notice %></p>

<h1 class="">Estatísticas do usuário</h1>

<div class="user-stats text-center img-responsive">
  <img class="img-responsive" src="/chart.png" style="max-width:750px;margin:14px;">
</div>


<br>
<div id="new-bath-link text-center">
  <%= link_to 'Voltar',new_user_bath_path,  { class: "btn-default", style: "text-decoration: none;" } %>
<div>